name: shop_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #Network
  dio: ^5.4.0
  #local database
  shared_preferences: ^2.2.3

  #firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  flutter_facebook_auth: ^7.0.0
  google_sign_in: ^6.2.1

  #StateManagement
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  
  #UI
  introduction_screen: ^3.1.12
  animated_splash_screen: ^1.3.0
  flutter_svg: ^2.0.9
  photo_view: ^0.15.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.1
  gif_view: ^0.4.3
  intl_phone_number_input: ^0.7.4
  flex_color_picker: ^3.5.1
  hexcolor: ^3.0.1
  slide_countdown: ^1.6.1






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metrophobic-Regular.ttf
    - family: ArchivoBlack
      fonts:
        - asset: assets/fonts/ArchivoBlack-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
